### ISSUE TITLE
첫 번 째 코드 리팩토링

### ISSUE THREAD

**Issue by osangu** [kodomomo/dsm-payments#17]
1. 문자열 정적으로 관리하기
2. 빌더 패턴 생성자로 변경하기

**Comment by mallycrip** [comment]
저는.. 개인적으로 리팩토링을 굳이 해야하나 라는 생각이 있습니다. 
만약 당장 사용할 것이라면 리팩토링 보다는 현재 니즈에 맞게 수정만 하고 추후에도 계속 사용되면 그때는 새로운 프로젝트를 만드는게 더 좋지 않을까 라는 생각이 있어요.

**Comment by mallycrip** [comment]
지금 해당 코드는 트랜잭션, 동시성 제어 등의 기본적인 처리도 되어있지 않고 방치가 너무 오래되었습니다. 
니즈에 맞게 수정하는 수준은 담당해줄 수 있는 사람이 있겠지만 리팩토링 같은 경우 사실상 코드 전체를 엎어야할 텐데 코드리뷰와 같이 기본적인 관리조차 담당해줄 수 있는 사람이 있을지 의문입니다.

**Comment by osangu** [comment]
2023년도 까지만 요구 사항을 반영하고, 2024년도 부터는 개발을 다시 진행해야 할 것 같습니다.
